name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-xenial

    steps:
    - uses: actions/checkout@v1
    - name: make
      run: USE_SINGLE_BUILDDIR=1 make release
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
